//获取网易热门歌单
export const NETEASE_HOT_SONG_LIST = 'NETEASE_HOT_SONG_LIST'
export const NETEASE_HOT_SONG_LIST_DONE = 'NETEASE_HOT_SONG_LIST_DONE'
export const NETEASE_HOT_SONG_LIST_FAIL = 'NETEASE_HOT_SONG_LIST_FAIL'
export const NETEASE_HOT_SONG_LIST_MORE = 'NETEASE_HOT_SONG_LIST_MORE'

//获取网易歌单详情
export const NETEASE_SONG_LIST_DETAIL = 'NETEASE_SONG_LIST_DETAIL'
export const NETEASE_SONG_LIST_DETAIL_DONE = 'NETEASE_SONG_LIST_DETAIL_DONE'
export const NETEASE_SONG_LIST_DETAIL_FAIL = 'NETEASE_SONG_LIST_DETAIL_FAIL'

//搜索网易云
export const NETEASE_SEARCH = 'NETEASE_SEARCH'
export const NETEASE_SEARCH_MORE = 'NETEASE_SEARCH_MORE'
export const NETEASE_SEARCH_NEW_DONE = 'NETEASE_SEARCH_NEW_DONE'
export const NETEASE_SEARCH_DONE = 'NETEASE_SEARCH_DONE'
export const NETEASE_SEARCH_FAIL = 'NETEASE_SEARCH_FAIL'

//获取网易云歌曲详细url
export const NETEASE_SONG_DETAIL = 'NETEASE_SONG_DETAIL'
export const NETEASE_SONG_DETAIL_DONE = 'NETEASE_SONG_DETAIL_DONE'
export const NETEASE_SONG_DETAIL_FAIL = 'NETEASE_SONG_DETAIL_FAIL'

//获取虾米热门歌单
export const XIAMI_HOT_SONG_LIST = 'XIAMI_HOT_SONG_LIST'
export const XIAMI_HOT_SONG_LIST_DONE = 'XIAMI_HOT_SONG_LIST_DONE'
export const XIAMI_HOT_SONG_LIST_FAIL = 'XIAMI_HOT_SONG_LIST_FAIL'
export const XIAMI_HOT_SONG_LIST_MORE = 'XIAMI_HOT_SONG_LIST_MORE'

//获取虾米歌单详情
export const XIAMI_SONG_LIST_DETAIL = 'XIAMI_SONG_LIST_DETAIL'
export const XIAMI_SONG_LIST_DETAIL_DONE = 'XIAMI_SONG_LIST_DETAIL_DONE'
export const XIAMI_SONG_LIST_DETAIL_FAIL = 'XIAMI_SONG_LIST_DETAIL_FAIL'

//搜索虾米
export const XIAMI_SEARCH = 'XIAMI_SEARCH'
export const XIAMI_SEARCH_MORE = 'XIAMI_SEARCH_MORE'
export const XIAMI_SEARCH_NEW_DONE = 'XIAMI_SEARCH_NEW_DONE'
export const XIAMI_SEARCH_DONE = 'XIAMI_SEARCH_DONE'
export const XIAMI_SEARCH_FAIL = 'XIAMI_SEARCH_FAIL'

//获取qq音乐热门歌单
export const QMUSIC_HOT_SONG_LIST = 'QMUSIC_HOT_SONG_LIST'
export const QMUSIC_HOT_SONG_LIST_DONE = 'QMUSIC_HOT_SONG_LIST_DONE'
export const QMUSIC_HOT_SONG_LIST_FAIL = 'QMUSIC_HOT_SONG_LIST_FAIL'
export const QMUSIC_HOT_SONG_LIST_MORE = 'QMUSIC_HOT_SONG_LIST_MORE'

//获取qq音乐歌单详情
export const QMUSIC_SONG_LIST_DETAIL = 'QMUSIC_SONG_LIST_DETAIL'
export const QMUSIC_SONG_LIST_DETAIL_DONE = 'QMUSIC_SONG_LIST_DETAIL_DONE'
export const QMUSIC_SONG_LIST_DETAIL_FAIL = 'QMUSIC_SONG_LIST_DETAIL_FAIL'

//播放器详情
export const SET_NE_PLAYER_DETAIL = 'SET_NE_PLAYER_DETAIL'
export const SET_XM_PLAYER_DETAIL = 'SET_XM_PLAYER_DETAIL'
export const SET_PLAYER_PAUSE = 'SET_PLAYER_PAUSE'
export const SET_PLAYER_RESUME = 'SET_PLAYER_RESUME'